
platform :ios, ‘8.0’

use_frameworks!

target 'testApp' do


pod 'AFNetworking', '~> 3.1.0'

pod 'MBProgressHUD', '~> 1.0.0'

pod 'Masonry', '~> 1.1.0'

pod 'SDWebImage', '~> 3.8.2'

pod 'MJRefresh', '~> 3.1.15'

pod 'YYKit', '~> 1.0.9'


end

